### ISSUE TITLE
How to setup with virtual env ?

### ISSUE THREAD

**Issue by anilshanbhag** [vorushin/sublimetext_python_checker#10]
Can you post some instruction to make it work in virtualenv ?

**Comment by vorushin** [comment]
If you installed pep8 and pyflakes into a separate virtualenv, you don't need to do anything specific. Just provide the full path to executables.

Example:

``` python
CHECKERS = [('/Users/vorushin/.virtualenvs/checkers/bin/pep8', []),
                ('/Users/vorushin/.virtualenvs/checkers/bin/pyflakes', [])]
```
