### ISSUE TITLE
Sublime 3 support

### ISSUE THREAD

**Issue by gcarvalho** [vorushin/sublimetext_python_checker#11]
Sublime 3 alpha is out. 
I tried to port your plugin over, but I don't know enough of sublime's api and inner workings.
Right now, after sorting the print() and regexp problems, I'm getting and "ValueError: icon must be a string" caused by :

``` python
   view.add_regions('python_checker_outlines',
        outlines,
        'keyword',
        sublime.DRAW_EMPTY | sublime.DRAW_OUTLINED)
```

... in line 98.

**Comment by vorushin** [comment]
Please take a loot at http://www.sublimetext.com/docs/3/api_reference.html Now fourth parameter is icon. You can prepend 'flags=' to a last parameter.

Thank you for you work on python3 compatible version of plugin. Ideally it should work for both python2/Sublime2 and python3/Sublime3. Please send me a pull request when it's ready. Feel free to ask additional questions.

**Comment by gcarvalho** [comment]
Thanks, I'll try.
I'm now running into a ST3 bug, where subprocess.Popen() always fails with a message along the lines of:

> dyld: lazy symbol binding failed: Symbol not found: _dirfd
>  Referenced from: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
>  Expected in: /usr/lib/libSystem.B.dylib

It seems to be specific to the OSX build in 10.7.5, but that is what I have at the moment, unfortunately...
There are more people reporting this.
